server:
  port: 8094
  servlet:
    context-path: /clinic
  
spring:
  application:
    name: clinic-service 

  datasource:
#    url: jdbc:mysql://localhost:3306/clinicServiceDataBase?createDatabaseIfNotExist=true
    url: jdbc:mysql://mysql3000.mysql.database.azure.com:3306/clinicServiceDataBase?createDatabaseIfNotExist=true
    username: mysql
    password: password@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
     ddl-auto: update
    properties:
     hibernate:
            database-platform: org.hibernate.dialect.MySQL8Dialect
           
swagger:
  url:
     productionURL: https://virtusa-clinic.learn.skillassure.com/clinic

  

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  file:
    name: inventory.log`
  pattern:
    console: '%d %-5level %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    '[org.springframework.web]': INFO
    '[com.ros.inventory]': DEBUG
    '[org.hibernate]': INFO
